import Link from "next/link"
import "./globals.css"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@/components/analytics"
import { ModeToggle } from "@/components/mode-toggle"
import ScrollToTopButton from "../components/ScrollToTopButton"
import '../Styles/fonts.css';




const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Nitin Sagar",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-[white] dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
        
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-xl md:max-w-4xl sm:max-w-2xl mx-auto py-10 px-4 ">
            <header>
              
              <div className="flex md:items-center justify-between">
                <ModeToggle />
                <nav className="ml-auto text-lg md:text-sm justify-between font-medium space-x-4 md:space-x-6">
                  <Link href="/">Home</Link>
                  <Link href="/Work">Resume</Link>
                  <Link href="/about">About</Link>
                
                </nav>
              </div>
            </header>
            <main className="">
            {children}
            <ScrollToTopButton />
            </main>
            
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  )
}

